SAMPLES: ['SLX-18968.UDP0231.HT3G5DMXX.s_2',
           'SLX-18968.UDP0239.HT3G5DMXX.s_2'] 

TOOL: {'delly', 'tiddit', 'sniffles'}
BUILD: "GRCh38"
COHORT: "WES" 
PAIRED: TRUE
GENOME: "../annotations/gatkresources/Homo_sapiens_assembly38.fasta"
EXCL: "human.hg38.excl.tsv"
RG: "A00489_467.HT3G5DMXX.2"
druggable: "druggable.hg38.csv"
