name: Tests for snakemake SV 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
            activate-conda: true
      - run: conda env update -n base -f environment.yml
      - name: Test with pytest
        run: pytest .tests/unit/ 
